spring:
  application:
    name: proyectoSpringBoot

  datasource:
    url: jdbc:postgresql://localhost:5432/ejspring
    username: postgres
    password: admin1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

server:
  port: 8080

  servlet:
    context-path: /product-api
